- name: check python installed
  stat:
    path: "/usr/local/bin/anyenv/envs/pyenv/shims/python"
  register: st_installed

- when: not st_installed.stat.exists
  block:
# (pyenv official) Suggested build environment
# https://github.com/pyenv/pyenv/wiki
  - name: (required) install library
    apt:
      # aptではwith_itemsの使用は非推奨になりました。v2.11で削除されます。
      name:
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - python3-dev
      - python3-pip
      state: present

  - name: install python
    shell: |-
        bash -lc "pyenv install -s {{ python_version }}"
    when: python_version is defined and

  - name: set pyenv global
    shell: |-
      bash -lc "pyenv global {{ python_global }}"
      # anyenv init -で実行しているので不要
      # bash -lc "pyenv rehash"
    when: python_global is defined

  - name: upgrade pip
    shell: |-
      bash -lc "pip install --upgrade pip"

  - name: install requirements.txt by pip
    pip:
      chdir: /vagrant
      requirements: ./requirements.txt
