- name: install boto3 aws-cli
  pip:
    name:
      - awscli
      - boto3
    state: present

- name: set profile.d/aws.sh for aws credential
  become: yes
  lineinfile:
    path=/etc/profile.d/aws.sh
    create=yes
    line={{ item }}
  with_items:
    - '# aws credentials'
    - 'export AWS_ACCESS_KEY_ID={{ aws_access_key_id }}'
    - 'export AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}'
    - 'export AWS_DEFAULT_REGION={{ aws_default_region }}'
    - 'export AWS_DEFAULT_OUTPUT={{ aws_default_output }}'
    - '# aws-cli completion'
    - 'complete -C $(which aws_completer) aws'