- name: apt-get update
  apt: update_cache=yes

- name: apt-get upgrade
  apt: upgrade=dist

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: uninstall Unnecessary command
  apt:
    name:
      - nano
    state: absent