terraform_version : '0.11.8'
terraform_platform : linux_amd64
terraform_mirror : https://releases.hashicorp.com/terraform
terraform_install_dir : /usr/local/bin

terraform_bin_with_version : 'terraform_{{ terraform_version }}'
terraform_zip: '{{ terraform_bin_with_version }}_{{ terraform_platform }}.zip'
terraform_url: '{{ terraform_mirror }}/{{ terraform_version }}/{{ terraform_zip }}'
terraform_bin_dir: '{{ terraform_install_dir }}/{{ terraform_bin_with_version }}'